### ISSUE TITLE
bsd's version of 'date' does not like supplied parameters

### ISSUE THREAD

**Issue by ericx** [glensc/monitoring-plugin-check_domain#44]
BSD's 'date' command wants different parameters to convert expiration to seconds.

intead of: `date +%s --date="$expiration"`

we need: `date -j -f %F $expiration +%s`

I'm using FreeBSD 10.1-RELEASE; but I assume the problem is common amongst freebsd, netbsd, openbsd and OSX (haven't tested). 

Sorry not to have written an elegant test to submit. I just hard coded the changes.

**Comment by glensc** [comment]
the BSD variant totally chokes GNU version:

```
$ date -j -f %F 123 +%s
date: invalid option -- 'j'
Try 'date --help' for more information.
```

so, we need platform detection, or porting the date call to awk

any suggestion how to detect your platforms?

**Comment by ericx** [comment]
I've been using Noah Friedman's `hosttype` script for years (found as `init-7.5/bin/hosttype` within `ftp://ftp.splode.com/pub/users/friedman/inits/init-7.5.tar.gz`). It's a stand-alone version of GNU's `config.guess`. It cough's up a string: `[arch]-[vendor]-[distro]` (e.g.: in my case, x86_64-pc-freebsd10.1). Might be a bit overkill and it certainly isn't mainstream; but it takes out all the heavy lifting of sussing your platform.

**Comment by glensc** [comment]
requiring user to install it is definitely overkill. but if it's installed by default in your systems, i could use that as indication.

**Comment by glensc** [comment]
hmm, maybe `date --help` or `date --version` detection? can you post yours?

**Comment by ericx** [comment]
It's a krufty old app. There is no `help` or `version` option:

     ** root@olivia2 ** /usr/ports/databases/phpmyadmin ** Mon Jun 29 10:07:58
    # date -h
    date: illegal option -- h
    usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
                [-f fmt date | [[[[[cc]yy]mm]dd]HH]MM[.ss]] [+format]
    [Exit 1 ]

**Comment by ericx** [comment]
hm..  The `-j` option might be unique to the BSD version and it has the polite aspect of instructing `date` specifically to **not** attempt to adjust the clock.

**Comment by ericx** [comment]
Latest FBSD man page:
https://www.freebsd.org/cgi/man.cgi?query=date

**Comment by glensc** [comment]
clock adjust may not be the issue (you must not run this plugin as `root`)

**Comment by Elyrith** [comment]
I haven't run FreeBSD (yet, soon), but it looks like it has the uname command to gather this info from. Perhaps a grep for "BSD"? I'll try it when I get a chance on a DigitalOcean droplet.

**Comment by Elyrith** [comment]
Ahh, I just created a FreeBSD 10.2 droplet with the following result:
```
$ uname -a | grep BSD
FreeBSD freebsd 10.2-RELEASE FreeBSD 10.2-RELEASE #0 r286666: Wed Aug 12 15:26:37 UTC 2015     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
```

**Comment by glensc** [comment]
what about [uname(1)](http://linux.die.net/man/1/uname)?

```
$ uname -s
Linux
```

**Comment by glensc** [comment]
I don't think it's worth the effort working on this. just install gnu version of date.
