### ISSUE TITLE
Date not reliably parsed (perhaps only on BSD) - need to remove whitespaces.

### ISSUE THREAD

**Issue by dgigante** [glensc/monitoring-plugin-check_domain#72]
We're having an issue running this on BSD (not withstanding the issue reported in #44 

Not sure whether it's a BSD vs Linux awk, but some whois servers (whois.nic.uk) are returning carriage returns which are not being removed (and maybe the BSD date formatting is more sensitive to.

I can give examples, but it should be obvious that the following fix would be a useful addition to make parsing a bit more robust:

    @@ -452,12 +452,12 @@ else
     	outfile=$(tempfile)
     	run_whois
     fi
    -expiration=$(get_expiration $outfile)
    +expiration=$(get_expiration $outfile | sed -E 's/[[:space:]]+//g')
     
     [ -   z "$expiration" ] && die "$STATE_UNKNOWN" "UNKNOWN - Unable to figure out expiration date for $domain Domain."

**Comment by glensc** [comment]
could you provide (attach to issue as .txt, .zip; or some other ways) raw output as such whois call?

**Comment by glensc** [comment]
Outdated. Re-create if still relevant.
