### ISSUE TITLE
domain interval

### ISSUE THREAD

**Issue by janarthananjana** [glensc/monitoring-plugin-check_domain#73]
When I add domains to nagios for first interval check time its working correctly and second check internal it goes to unknown state like unable to figure out . I attached screen shot please look it
![t](https://user-images.githubusercontent.com/28565699/27476229-33ba96e6-5808-11e7-9969-210ce1edf45e.png)
![t1](https://user-images.githubusercontent.com/28565699/27476228-33b9e67e-5808-11e7-8750-fdfb18dbf4e9.png)

**Comment by glensc** [comment]
not enough information. impossible to reproduce

**Comment by janarthananjana** [comment]
I set interval for 5minutes
For first time nagios check domain its looks good
for second check it goes to unable to figure out expiration date as you see above


Domain is   .pl domains

**Comment by ramyacharan** [comment]
Same issue for me also for .ie domains
