### ISSUE TITLE
Some domains get "UNKNOWN - WHOIS exited with error 1"

### ISSUE THREAD

**Issue by luizexcession** [glensc/monitoring-plugin-check_domain#75]
Even if the domain exist, they still get these `UNKNOWN` errors.

Example of domains:

- godaddy.com
- aframe.com
- google.com

**Comment by mjsmedley** [comment]
Same issue, but any domain.

UNKNOWN - WHOIS exited with error 1.

**Comment by cvandyke1217** [comment]
I am also seeing this.  I can manually run a whois lookup from the same server and get expected results, but not using the plugin.

**Comment by grepcatman** [comment]
I'm getting the same issue, on .com and .net, but not .org.  I manually ran whois on each and the domain expiry line looks fairly identical:
` Domain Name: example.ORG Registry Expiry Date: 2018-05-19T21:55:44Z
 Domain Name: example.COM Registry Expiry Date: 2018-05-20T01:28:06Z
 Domain Name: example.NET Registry Expiry Date: 2018-05-19T20:57:43Z`

**Comment by zefsauce** [comment]
Same issue, but it only seems to affect .COM and .NET.

UNKNOWN - WHOIS exited with error 1.

**Comment by PasiJarnstedt** [comment]
It seems that whois.networksolutions.com (that whois seems to use with default) does not return answers anymore. I don't know why or if this is permanent.

calling whois from command line will redirect queries to "whois.verisign-grs.com" it seems that calling whois from script does not do this substitute.

I Added following lines after line 215, after setup_whois (this is not copy paste forgive for typos):
if [ -z $server ]
then 
    if echo "$domain" | grep -q -e ".com$" -e ".net$" -e ".edu$"
    then
        server="whois.verisign-grs.com"
    fi
fi

This will change the server for .com,.net,.edu domains if the server is not previously set (by -s parameter on check_domain)

**Comment by mjsmedley** [comment]
This works.  Thanks.  Are you the author of this script?

**Comment by mjsmedley** [comment]
Doesn't work with .TV domains though.

**Comment by luizexcession** [comment]
Thank you @PasiJarnstedt, it fixes my issues with `.com`. Cheers, mate.

**Comment by glensc** [comment]
you should use server option to check_domain script:

```
-s, --server
     Specific Whois server for domain name check
```

and probably whois tool needs to be updated doing this itself. anyone want to submit bug there?

perhaps it's already fixed in 5.2.17? 
https://github.com/rfc1036/whois/commit/6e23999a24d8816564cc3f59fe8c99274c0c8dae

**Comment by glensc** [comment]
fixed with whois-5.2.17, until then use `-s` (or `--server`) option to force whois server.
https://github.com/rfc1036/whois/pull/56

```
➔ ./check_domain.sh -d google.com                                                        
UNKNOWN - WHOIS exited with error 1.

➔ q whois
whois-5.2.15-1.x86_64

➔ ./check_domain.sh -d google.com
OK - Domain google.com will expire in 1130 days (2020-09-14). | domain_days_until_expiry=1130;30;7

➔ q whois
whois-5.2.17-1.x86_64

➔
```

**Comment by zefsauce** [comment]
CentOS 7.3 x64 - working again after removing the jwhois rpm.

**Comment by ramyacharan** [comment]
Hi I want to know the expiry date of .au and .eu domains unable(UNKNOWN - Unable to figure out expiration date for *****.eu domain) to get them from this script need to add different servers for those requests i think , as i have 0 knowledge in scripting so could you please provide me the updated script , so that it will be very helpful to me.
Thanks in advance
