### ISSUE TITLE
 invalid date for *.ru domain

### ISSUE THREAD

**Issue by pdapnz** [glensc/monitoring-plugin-check_domain#77]
```
./check_domain.sh -d yandex.ru
date: invalid date `2018-09-30T21:00:00Z'
```
This comment solve problem:

https://exchange.nagios.org/directory/Plugins/Internet-Domains-and-WHOIS/check_domain/details#rev-4119

**Comment by glensc** [comment]
Outdated. Re-create if still relevant. Preferably just send a fix yourself.
