### ISSUE TITLE
UNKNOWN - Unable to figure out expiration date for " ****.eu" Domain

### ISSUE THREAD

**Issue by ramyacharan** [glensc/monitoring-plugin-check_domain#81]
Hi @glensc & @PasiJarnstedt
I want to know the expiry date of .au and .eu domains , unable to get them from this script  (error:UNKNOWN - Unable to figure out expiration date for *****.eu domain) need to add different servers for those requests i think , as i have zero knowledge in scripting so could you please provide me the updated script , so that it will be very helpful to me. And for .ie domains it is not working all the time some time it is giving error like unable to figure out expiry and some time it is providing expiry date. 
Thanks in advance

**Comment by ramyacharan** [comment]
@ @glensc

**Comment by C-Bam** [comment]
I just tested, and I think it is not related to the script, but to the registrar it self.

Try to call `whois europa.eu` for instance and you'll see there are missing informations

**Comment by PasiJarnstedt** [comment]
It seems that eurid.eu does not even give domain expiry date in their website. So for that part no amount of scripting does not help.

For .ie domain  I cannot reproduce this error. Does it give error on specific domain or just a random time.

**Comment by pezzotto** [comment]
Hi guys, i'm also trying to make this plugin working with .eu domain?

Any suggestion?

**Comment by glensc** [comment]
It might help to add support to whois client:
- https://github.com/rfc1036/whois

**Comment by glensc** [comment]
Outdated. Re-create if still relevant. Preferably just send a fix yourself.
