### ISSUE TITLE
Add support for LibreNMS

### ISSUE THREAD

**Issue by SirMaple** [glensc/monitoring-plugin-check_domain#89]
Would it be possible to add support for LibreNMS?

In LibreNMS a script called [check_services.php](https://github.com/librenms/librenms/blob/96d65d1cc3154470d619ded831a9a81565bf0360/check-services.php) calls the required "check" script. It **always** passes `-H hostname.example.com`. But when it calls the check_domain script it fails and returns an error `check_domain.sh: invalid option -- 'H'`.

The check_domain.sh script works correctly if I call it manually from the command line
`./check_domain.sh -d google.ca -C /tmp -a 1`
`OK - Domain google.ca will expire in 63 days (2019-04-28). | domain_days_until_expiry=63;30;7`

Would it be possible to have the check_domain.sh script updated to ignore the `-H hostname.example.com` so that it won't return an error?

**Comment by glensc** [comment]
I think you need to have `-H` alias to `-d`, send PR.

**Comment by SirMaple** [comment]
I've corrected the link. Sorry about that.

I have no clue how to create an alias. I'm a newb when it comes to coding.

**Comment by Cool76** [comment]
hello , could you teach me how to do ? i am not familiar on coding

Thanks

**Comment by glensc** [comment]
a quick search on [`shell syntax`](https://lmgtfy.com/?q=shell+syntax):
- https://tiswww.case.edu/php/chet/bash/bashref.html
- https://www.gnu.org/software/bash/manual/html_node/Shell-Syntax.html

the file you need to edit is [`check_domain.sh`](https://github.com/glensc/monitoring-plugin-check_domain/edit/master/check_domain.sh)
